InvoiceManager.WebSite/Controllers/BarcodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FacturationWebSite.Models;

namespace InvoiceManager.WebSite.Controllers
{
    public class BarcodeController : Controller
    {
        private readonly MvcAppContext _context;

        public BarcodeController(MvcAppContext context)
        {
            _context = context;
        }

        // GET: Barcode
        public async Task<IActionResult> Index()
        {
            var MvcAppContext = _context.Barcode.Include(b => b.Customer).Include(b => b.Product);
            return View(await MvcAppContext.ToListAsync());
        }

        // GET: Barcode/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var barcode = await _context.Barcode
                .Include(b => b.Customer)
                .Include(b => b.Product)
                .SingleOrDefaultAsync(m => m.BarcodeId == id);
            if (barcode == null)
            {
                return NotFound();
            }

            return View(barcode);
        }

        // GET: Barcode/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Set<Customer>(), "CustomerId", "Name");
            ViewData["ProductId"] = new SelectList(_context.Set<Product>(), "ProductId", "Description");
            return View();
        }

        // POST: Barcode/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BarcodeId,CustomerId,ProductId")] Barcode barcode)
        {
            if (ModelState.IsValid)
            {
                _context.Add(barcode);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Set<Customer>(), "CustomerId", "Name", barcode.CustomerId);
            ViewData["ProductId"] = new SelectList(_context.Set<Product>(), "ProductId", "Description", barcode.ProductId);
            return View(barcode);
        }

        // GET: Barcode/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var barcode = await _context.Barcode.SingleOrDefaultAsync(m => m.BarcodeId == id);
            if (barcode == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Set<Customer>(), "CustomerId", "Name", barcode.CustomerId);
            ViewData["ProductId"] = new SelectList(_context.Set<Product>(), "ProductId", "Description", barcode.ProductId);
            return View(barcode);
        }

        // POST: Barcode/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BarcodeId,CustomerId,ProductId")] Barcode barcode)
        {
            if (id != barcode.BarcodeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(barcode);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BarcodeExists(barcode.BarcodeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Set<Customer>(), "CustomerId", "Name", barcode.CustomerId);
            ViewData["ProductId"] = new SelectList(_context.Set<Product>(), "ProductId", "Description", barcode.ProductId);
            return View(barcode);
        }

        // GET: Barcode/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var barcode = await _context.Barcode
                .Include(b => b.Customer)
                .Include(b => b.Product)
                .SingleOrDefaultAsync(m => m.BarcodeId == id);
            if (barcode == null)
            {
                return NotFound();
            }

            return View(barcode);
        }

        // POST: Barcode/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var barcode = await _context.Barcode.SingleOrDefaultAsync(m => m.BarcodeId == id);
            _context.Barcode.Remove(barcode);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BarcodeExists(int id)
        {
            return _context.Barcode.Any(e => e.BarcodeId == id);
        }

		// GET: Barcode/Print
		[ViewLayout("_PrintLayout")]
		public async Task<IActionResult> Print()
		{
			var MvcAppContext = _context.Barcode.Include(b => b.Customer).Include(b => b.Product).OrderBy(b => b.Customer.Name).ThenBy(b => b.Product.Description);
			return View(await MvcAppContext.ToListAsync());
		}
	}
}

InvoiceManager.WebSite/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FacturationWebSite.Models;

namespace InvoiceManager.WebSite.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly MvcAppContext _context;

        public InvoiceController(MvcAppContext context)
        {
            _context = context;
        }

        // GET: Invoice
        public async Task<IActionResult> Index()
        {
            var MvcAppContext = _context.Invoice.Include(i => i.Customer);
            return View(await MvcAppContext.ToListAsync());
        }

        // GET: Invoice/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice
                .Include(i => i.Customer)
                .SingleOrDefaultAsync(m => m.InvoiceId == id);

			var invoiceLine = _context.InvoiceLine.Include(il => il.Delivery).Where(il => il.InvoiceId == invoice.InvoiceId && il.Quantity > 0).OrderBy(il=>il.Delivery.Date).ToList();

			if (invoice == null)
            {
                return NotFound();
            }

			var invoiceViewModel = new InvoiceViewModel();

			invoiceViewModel.Invoice = invoice;
			invoiceViewModel.InvoiceLines = invoiceLine;
            invoiceViewModel.Subtotal = invoiceLine.Sum(il => (il.Price * il.Quantity));
            invoiceViewModel.Total = invoiceViewModel.Subtotal + invoiceViewModel.Discount;
            invoiceViewModel.Discount = 0;

			ViewData["DateList"] = _context.Deliveries.Where(d => d.Date >= DateTime.Parse(invoice.StartPeriod) && d.Date <= DateTime.Parse(invoice.EndPeriod)).OrderBy(d => d.Date).Select(d => new SelectListItem() { Text = d.Date.ToString("D"), Value = d.DeliveryId.ToString() }).ToList();
			ViewData["NearestDate"] = _context.Deliveries.Where(d => d.Date > DateTime.Now).OrderBy(d => d.Date).Select(d => d.DeliveryId).FirstOrDefault();


			return View(invoiceViewModel);
        }

		

// GET: Invoice/Print
[ViewLayout("_PrintLayout")]
		public async Task<IActionResult> Print(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var invoice = await _context.Invoice
				.Include(i => i.Customer)
				.SingleOrDefaultAsync(m => m.InvoiceId == id);

			var invoiceLine = _context.InvoiceLine.Include(il => il.Delivery).Where(il => il.InvoiceId == invoice.InvoiceId && il.Quantity > 0).OrderBy(il => il.Delivery.Date).ToList();

			if (invoice == null)
			{
				return NotFound();
			}

			var invoiceViewModel = new InvoiceViewModel();

			invoiceViewModel.Invoice = invoice;
			invoiceViewModel.InvoiceLines = invoiceLine;
			invoiceViewModel.Subtotal = invoiceLine.Sum(il => (il.Price * il.Quantity));
			invoiceViewModel.Total = invoiceViewModel.Subtotal + invoiceViewModel.Discount;
			invoiceViewModel.Discount = 0;

			return View(invoiceViewModel);
		}
		

		// GET: Invoice/Create
		public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Set<Customer>(), "CustomerId", "Name");
            return View();
        }

        // POST: Invoice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("InvoiceId,CustomerId,Ref,CreationDate,StartPeriod,EndPeriod,Status")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                _context.Add(invoice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Set<Customer>(), "CustomerId", "Name", invoice.CustomerId);
            return View(invoice);
        }

        // GET: Invoice/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice.SingleOrDefaultAsync(m => m.InvoiceId == id);
            if (invoice == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Set<Customer>(), "CustomerId", "Name", invoice.CustomerId);
            return View(invoice);
        }

        // POST: Invoice/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("InvoiceId,CustomerId,Ref,CreationDate,StartPeriod,EndPeriod,Status")] Invoice invoice)
        {
            if (id != invoice.InvoiceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(invoice);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InvoiceExists(invoice.InvoiceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Set<Customer>(), "CustomerId", "Name", invoice.CustomerId);
            return View(invoice);
        }

        // GET: Invoice/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var invoice = await _context.Invoice
                .Include(i => i.Customer)
                .SingleOrDefaultAsync(m => m.InvoiceId == id);
            if (invoice == null)
            {
                return NotFound();
            }

            return View(invoice);
        }

        // POST: Invoice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var invoice = await _context.Invoice.SingleOrDefaultAsync(m => m.InvoiceId == id);
            _context.Invoice.Remove(invoice);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InvoiceExists(int id)
        {
            return _context.Invoice.Any(e => e.InvoiceId == id);
        }

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult NewLine(int DeliveryId, string Description, double Price, int Quantity, int InvoiceId)
		{
			InvoiceLine returnVal = new InvoiceLine();

			returnVal.InvoiceId = InvoiceId;
			returnVal.DeliveryId = DeliveryId;
			returnVal.CreationDate = DateTime.Now;
			returnVal.Description = Description;
			returnVal.Quantity = Quantity;
			returnVal.Price = Price;

			_context.InvoiceLine.Add(returnVal);
			_context.SaveChanges();


			return Json(returnVal);
		}

		[HttpPost]
		public async Task<IActionResult> ModifyLine(int InvoiceLineId, int Quantity)
		{
			var InvoiceLine = _context.InvoiceLine.FirstOrDefault(il => il.InvoiceLineId == InvoiceLineId);

			if (InvoiceLine != null)
			{
				InvoiceLine.Quantity = Quantity;

				_context.Update(InvoiceLine);
				await _context.SaveChangesAsync();
			}

			return Json(true);

		}
	}
}

InvoiceManager.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FacturationWebSite</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/dashboard.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
	<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
		<a class="navbar-brand col-sm-3 col-md-2 mr-0"  asp-area="" asp-controller="Home" asp-action="Index">Facturation manager</a>
		<input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
		<ul class="navbar-nav px-3">
			<li class="nav-item text-nowrap">
				<a class="nav-link" href="#">Sign out</a>
			</li>
		</ul>
	</nav>
	<div class="container-fluid">
		<div class="row">
			<nav class="col-md-2 d-none d-md-block bg-light sidebar">
				<div class="sidebar-sticky">
					<ul class="nav flex-column">
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
								<span class="fas fa-home"></span>
								Accueil
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Invoice" asp-action="Index">
								<span class="fas fa-file-alt"></span>
								Factures
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Customer" asp-action="Index">
								<span class="fas fa-building"></span>
								Clients
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">
								<span class="fas fa-shopping-bag"></span>
								Produits
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Barcode" asp-action="Index">
								<span class="fas fa-barcode"></span>
								Code-Barres
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="Delivery" asp-action="Index">
								<span class="fas fa-truck"></span>
								Livraisons
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" asp-area="" asp-controller="CustomerPrice" asp-action="Index">
								<span class="fas fa-building"></span>
								Prix spécifique par clients
							</a>
						</li>
					</ul>
				</div>
			</nav>
			
			<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
				@RenderBody()
				


			</main>
		</div>
	</div>
	

	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.min.js"></script>
		<script src="~/lib/moment/moment.min.js"></script>
		<script src="~/lib/jquery.fullCalendar/fullcalendar.min.js"></script>
		<script src='~/lib/jquery.fullCalendar/locale-all.js'></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
		<link rel='stylesheet' href='~/lib/jquery.fullCalendar/fullcalendar.min.css' />
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>


	</environment>
	<environment exclude="Development">
		<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
				asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
				asp-fallback-test="window.jQuery"
				crossorigin="anonymous"
				integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
		</script>
		<script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
				asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
				asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
				crossorigin="anonymous"
				integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
		</script>
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>

InvoiceManager.WebSite/Views/Shared/_PrintLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FacturationWebSite</title>

</head>
<body>
	@RenderBody()
			
	<environment include="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
	</environment>
	<environment exclude="Development">
		<script src="~/lib/jquery/dist/jquery.js"></script>
	</environment>

	@RenderSection("Scripts", required: false)
</body>
</html>